added checking profit command
Coflnet/discord-bot-node pull request #30
Opened 2022-01-22 03:31 UTC by tentamens

2022-01-24 08:09 UTC, matthias-luger requested changes

2022-01-24 08:09 UTC, matthias-luger commented on discordbotforcofl.code-workspace
> +{
please dont commit local vscode files

2022-01-24 08:09 UTC, matthias-luger commented on bot.js
> +    if (message.channel.id === '922237524989075476')
1. Please add brackets, as I dont think this if will even work like you would expect. And even if it would, without brackets it's highly dangerous and absolutely unreadable.
2. Please use the .env file for channel-ids

2022-01-24 08:09 UTC, matthias-luger commented on bot.js
> +    let split = text.split(' ');
Did you test this again? I think you removed/forgot to define `text`
I think you need to use `message.text.content`

2022-01-24 08:09 UTC, matthias-luger commented on bot.js
> +            if (res.status === 500) {
Technically a status code of 500 could mean a bunch of things. We just expect there to be no user with the name. But there could be another error. 
Please check the slug for that.
-> Kinda my mistake, as I helped you implement it that way, but I forgot to improve this solution

2022-01-24 09:14 UTC, matthias-luger commented
@tentamens Btw. it would be amazing if you could use the discord slash commands instead of reacting to a specific message.
https://discordjs.guide/interactions/registering-slash-commands.html#guild-commands

2022-01-24 17:13 UTC, tentamens commented
> @tentamens Btw. it would be amazing if you could use the discord slash commands instead of reacting to a specific message. https://discordjs.guide/interactions/registering-slash-commands.html#guild-commands

2022-01-25 16:45 UTC, matthias-luger requested changes

2022-01-25 16:45 UTC, matthias-luger commented on updateCommands.js
> +const clientId = '903860869090381894';
These two Ids need to come from the .env file

2022-01-25 16:45 UTC, matthias-luger commented on answer.json
> +        "question": [
Did you test these? How should they work? 
You have `get` in the question, but also in the blacklist

(Applies to all the questions below)

2022-01-25 20:06 UTC, merged