added days for profit command
Coflnet/discord-bot-node pull request #44
Opened 2022-02-20 18:37 UTC by tentamens

2022-02-22 09:35 UTC, Ekwav requested changes

2022-02-22 09:35 UTC, Ekwav commented on commands/profitCommands.js
> +            .setRequired(true)
Why do you want to require users to input a value when you can default to 7 days?

2022-02-22 09:35 UTC, Ekwav commented on commands/profitCommands.js
> +            return replyProfitEmbed(interaction, playerResponse[0].uuid, name, playerData.totalProfit, days, isEphemeral);
When passing days > 7 this will crash because the API will return an error Response. 
If there is an error message it should be displayed to the user

2022-02-22 16:15 UTC, tentamens commented on commands/profitCommands.js
> +            .setRequired(true)
Sounds fine to me I’ll try and add it

2022-02-23 17:44 UTC, matthias-luger commented on commands/profitCommands.js
> +        .addField(`${playerName} has made`, '**' + `${formatToPriceToShorten(totalProfit, 0)}` + '**' + ' in the last ' + `${days}`)
You are missing the string 'days' at the end.
The text would currently look like this: `Test has made **100M** in the last 7`

2022-02-23 17:46 UTC, matthias-luger commented on commands/profitCommands.js
> +        .addField(`${playerName} has made`, '**' + `${formatToPriceToShorten(totalProfit, 0)}` + '**' + ' in the last ' + `${days}`)
By using string interpolation you dont need to concat the strings with '+'.

2022-02-23 20:41 UTC, Ekwav commented on commands/profitCommands.js
> +        .addField(`${playerName} has made`, '**' + `${formatToPriceToShorten(totalProfit, 0)}` + '**' + ' in the last ' + `${days}`)
Ie you can remove the backticks, single quotes and plus between the values @tentamens

2022-02-24 17:05 UTC, merged